name: Checkout
on: [push]

jobs:
  checkout_and_display_files:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before Checkout
        run: ls -la

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List Files After Checkout
        run: ls -la
