name: Workflow Demo 1
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Run a String
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          node -v
          npm -v
  parallel-job-macos:
    runs-on: macos-latest
    steps:
      - name: view SW Version
        run: sw_vers
  dependent-job:
    runs-on: windows-latest
    needs: [run-shell-commands]
    steps:
      - name: Echo a string
        run: Write-Output "Windows String"
