name: Repository Events
on: 
  push:
  pull_request:
  issues:

jobs:
  checkout_list:
    runs-on: ubuntu-latest
    steps:
      - name: Display GitHub context
        run: |
          echo "Commit SHA: $GITHUB_SHA"
          echo "Ref: $GITHUB_REF"

      - name: Checkout Repository
        uses: actions/checkout@v5
