name: Repository Events

on:
  push:
  pull_request:
    types: [opened, reopened, closed]
  issues:
    types: [opened, closed]

jobs:
  Checkout-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Print Git info
        run: |
          echo "SHA: $GITHUB_SHA"
          echo "Ref: $GITHUB_REF"
